version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    exclude-paths:
      - "src/it/**"
      - "src/test/projects/**"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
